# Generated by Django 2.0.4 on 2018-04-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoAssentamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Código do PA')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do PA')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('data_criacao', models.DateField(verbose_name='Data de Criação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto de Assentamento',
                'verbose_name_plural': 'Projetos de Assentamento',
                'ordering': ['codigo'],
            },
        ),
    ]
