# Generated by Django 2.0.4 on 2018-04-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoassentamento',
            name='contrato',
            field=models.CharField(default='', max_length=15, verbose_name='Contrato'),
            preserve_default=False,
        ),
    ]
