# Generated by Django 2.0.4 on 2018-04-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projetoassentamento_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoassentamento',
            name='contrato',
            field=models.IntegerField(verbose_name='Contrato'),
        ),
    ]
