# Generated by Django 2.0.4 on 2018-04-24 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180424_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.IntegerField(verbose_name='Qual documento o lote possui?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Qual documento o lote possui',
                'verbose_name_plural': 'Quais documentos o lote possui',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sipra', models.CharField(max_length=15, verbose_name='Código SIPRA')),
                ('area', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Área (ha)')),
                ('numero', models.IntegerField(verbose_name='Lote N.º')),
                ('entrevistador', models.CharField(max_length=50, verbose_name='Nome do Entrevistador')),
                ('coordenada_x', models.BigIntegerField(verbose_name='Coordenada "X"')),
                ('coordenada_y', models.BigIntegerField(verbose_name='Coordenada "Y"')),
                ('existe_outra_familia_que_mora_no_lote', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Existe outra família que mora na parcela/lote?')),
                ('cad_unico', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='CAD - Único')),
                ('ocupante_irregular', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Ocupante irregular?')),
                ('ocupante_irregular_tempo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Em caso afirmativo, há quanto tempo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.AlterField(
            model_name='projetoassentamento',
            name='contrato',
            field=models.IntegerField(choices=[(10, '10.000/2015'), (11, '11.000/2015'), (18, '18.000/2015')], verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='documentolote',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.Lote', verbose_name='Lote'),
        ),
    ]
