# Generated by Django 2.0.4 on 2018-04-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180424_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='projeto_assentamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.ProjetoAssentamento', verbose_name='PA'),
            preserve_default=False,
        ),
    ]
