# Generated by Django 2.0.4 on 2018-04-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lote_projeto_assentamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='existe_outra_familia_que_mora_no_lote',
            new_name='outra_familia_no_lote',
        ),
    ]
