# Generated by Django 2.0.4 on 2018-04-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180424_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentolote',
            options={'verbose_name': 'Qual documento o lote possui?', 'verbose_name_plural': 'Quais documentos o lote possui?'},
        ),
        migrations.AlterField(
            model_name='documentolote',
            name='tipo_documento',
            field=models.IntegerField(choices=[(1, 'Contrato de Assentamento'), (2, 'Contrato de Concessão de Uso - CCU'), (3, 'Título Definitivo - não registrado'), (4, 'Título Definitivo - registrado cartório'), (5, 'Matrícula da Propriedade')], verbose_name='Qual documento o lote possui?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cad_unico',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='CAD - Único'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='ocupante_irregular',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='Ocupante irregular?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='outra_familia_no_lote',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='Existe outra família que mora na parcela/lote?'),
        ),
    ]
