# Generated by Django 2.0.4 on 2018-04-24 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180424_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beneficio', models.IntegerField(choices=[(1, 'Aposentadoria por tempo de serviço/idade'), (2, 'Aposentadoria por invalidez'), (3, 'Auxílio maternidade'), (4, 'Bolsa família'), (5, 'Bolsa verde'), (6, 'Outros')], verbose_name='Qual documento o lote possui?')),
                ('outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Qual o tipo de benefício?',
                'verbose_name_plural': 'Quais os tipos de benefício?',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='recebe_beneficio_social',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Algum dos membros da família recebe algum tipo de Benefício Social?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiosocial',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='core.Lote', verbose_name='Lote'),
        ),
    ]
