# Generated by Django 2.0.4 on 2018-04-24 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_autodeclaracaoetnia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstruturaOrganizativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estrutura_organizativa', models.IntegerField(choices=[(1, 'Associação omunitária'), (2, 'Cooperativas (produção, créditos, etc.)'), (3, 'Associação ou grupos de mulheres'), (4, 'Núcleos de base ligados aos movimentos'), (5, 'Trabalhos coletivos (ajuda mútua) "multirões"'), (6, 'Grupos vinculados à igreja (pastoral, etc.)'), (7, 'Grupos de jovens'), (8, 'Grupos de saúde (pastoral, farmácia viva)'), (9, 'Associação de pais e mestres e outros'), (10, 'Grupos de laser e cultura')], verbose_name='Estrutura organizativa')),
                ('frequencia', models.IntegerField(choices=[(1, 'Frequente (>70%)'), (2, 'Regularmente (50% a 70%)'), (3, 'Raramente (<50%)'), (4, 'Não Participa')], verbose_name='Frequência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estruturasOrganizativas', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Das estruturas organizativas internas ao assentamento diga qual existe no assentamento e de quais os membros da família participam',
                'verbose_name_plural': 'Das estruturas organizativas internas ao assentamento diga qual existe no assentamento e de quais os membros da família participam',
            },
        ),
    ]
