# Generated by Django 2.0.4 on 2018-04-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_estruturaorganizativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='moradia_assentamento',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Possui moradia no assentamento?'),
            preserve_default=False,
        ),
    ]
