# Generated by Django 2.0.4 on 2018-04-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lote_moradia_assentamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='tipo_parede_externa',
            field=models.IntegerField(blank=True, choices=[(1, 'Alvenaria'), (2, 'Tábuas / Madeira'), (3, 'Tapumes ou chapas de madeira'), (4, 'Folha de zinco'), (5, 'Barro ou adobe'), (6, 'Lona'), (7, 'Outros')], null=True, verbose_name='Qual tipo de parede externa predominante da moradia?'),
        ),
    ]
