# Generated by Django 2.0.4 on 2018-04-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lote_tipo_parede_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='tipo_instalacao_eletrica',
            field=models.IntegerField(blank=True, choices=[(1, 'Não instalada'), (2, 'Instalada apenas para moradia'), (3, 'Instalada para moradia e outros usos'), (4, 'Outros')], null=True, verbose_name='Instalação de energia elétrica?'),
        ),
    ]
