# Generated by Django 2.0.4 on 2018-04-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lote_tipo_instalacao_eletrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='tipo_instalacao_sanitaria',
            field=models.IntegerField(blank=True, choices=[(1, 'Banheiro com fossa séptica'), (2, 'Banheiro com fossa negra'), (3, 'Privada / latrina'), (4, 'Nenhuma')], null=True, verbose_name='Qual é o tipo de instalação sanitária?'),
        ),
    ]
