# Generated by Django 2.0.4 on 2018-04-24 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lote_tipo_instalacao_sanitaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_agua', models.IntegerField(choices=[(1, 'Poço artesiano'), (2, 'Nascente ou vertente'), (3, 'Córregos ou Rios'), (4, 'Capitação de água da chuva'), (5, 'Açude / Barreiro'), (6, 'Poço comum'), (7, 'Depósito coletivo'), (8, 'Rede de água encanada'), (9, 'Outra')], verbose_name='Fonte de água')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontesAgua', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'De onde vem a água que abastece a família?',
                'verbose_name_plural': 'De onde vem a água que abastece a família?',
            },
        ),
    ]
