# Generated by Django 2.0.4 on 2018-04-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fonteagua'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamentoAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamento_agua', models.IntegerField(choices=[(1, 'Não há tratamento'), (2, 'Cloração'), (3, 'Fervura'), (4, 'Filtragem'), (5, 'Dessalinização'), (6, 'Outra')], verbose_name='Forma de tratamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentosAgua', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Qual a forma tratamento da água para consumo?',
                'verbose_name_plural': 'Qual a forma tratamento da água para consumo?',
            },
        ),
    ]
