# Generated by Django 2.0.4 on 2018-04-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tratamentoagua'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='localizacao_fonte_agua',
            field=models.IntegerField(choices=[(1, 'Dentro do seu lote'), (2, 'Fora do seu lote')], default=0, verbose_name='Onde está localizada a fonte de água que abastece sua residência?'),
            preserve_default=False,
        ),
    ]
