# Generated by Django 2.0.4 on 2018-04-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lote_localizacao_fonte_agua'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='abastecimento_agua_suficiente',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='A água que abastece a residência é suficiente?'),
            preserve_default=False,
        ),
    ]
