# Generated by Django 2.0.4 on 2018-04-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_lote_abastecimento_agua_suficiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='utilizacao_mesma_fonte_agua',
            field=models.IntegerField(choices=[(1, 'Nenhuma'), (2, 'Uma ou outra família, além da sua família'), (3, 'Mais de uma')], default=1, verbose_name='Quantas famílias (além da sua) fazem o uso da mesma fonte de água que abastece o seu lote?'),
            preserve_default=False,
        ),
    ]
