# Generated by Django 2.0.4 on 2018-04-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_lote_utilizacao_mesma_fonte_agua'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='utilizacao_mesma_fonte_agua_quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantas famílias?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='utilizacao_mesma_fonte_agua',
            field=models.IntegerField(choices=[(1, 'Nenhuma'), (2, 'Uma outra família, além da sua família'), (3, 'Mais de uma')], verbose_name='Quantas famílias (além da sua) fazem o uso da mesma fonte de água que abastece o seu lote?'),
        ),
    ]
