# Generated by Django 2.0.4 on 2018-04-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180424_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='utilizacao_mesma_fonte_agua',
            new_name='quantas_familias_utilizam_mesma_fonte_agua',
        ),
        migrations.AlterField(
            model_name='lote',
            name='utilizacao_mesma_fonte_agua_quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mais de uma. Quantas?'),
        ),
    ]
