# Generated by Django 2.0.4 on 2018-04-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180425_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='agua_para_animais_plantio',
            field=models.IntegerField(choices=[(1, "Sim, os animais vão até um curso d'água ou represa"), (2, "Sim, a água é puxada de um curso d'água ou represa"), (3, 'Sim, temos um poço exclusivo para os animais'), (4, 'Sim, é a mesma água que vem para a casa'), (5, 'Não há água para animais'), (6, 'Sim, existe água para plantio(s) irrigado(s)'), (7, 'Não existe água para plantio(s) irrigado(s)'), (8, 'Outros')], default=0, verbose_name='No lote tem água para os animais / Plantio?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='agua_para_animais_plantio_outros',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Água para animais/plantio (Outros)'),
        ),
    ]
