# Generated by Django 2.0.4 on 2018-04-25 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180425_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstrucaoLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construcao_no_lote', models.IntegerField(choices=[(1, 'Galpão'), (2, 'Curral'), (3, 'Chiqueiro'), (4, 'Galinheiro'), (5, 'Segunda casa'), (6, 'Represa'), (7, 'Espaço para cultos religiosos'), (8, 'Estabelecimento comercial'), (9, 'Agroindústria'), (10, 'Outros')], verbose_name='Construção')),
                ('outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construcoesLote', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'O que tem construído no lote?',
                'verbose_name_plural': 'O que tem construído no lote?',
            },
        ),
    ]
