# Generated by Django 2.0.4 on 2018-04-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_construcaolote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BemProdutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bem_produtivo', models.IntegerField(choices=[(1, 'Trator'), (2, 'Caminhão'), (3, 'Caminhonete'), (4, 'Arado / grade'), (5, 'Plantadeira / adubadeira'), (6, 'Pulverizador "tratorizado"'), (7, 'Carroça ou carro de boi'), (8, 'Arado de tração animal'), (9, 'Triturador'), (10, 'Resfriador de leite'), (11, 'Cochos'), (12, 'Calcariadora'), (13, 'Bomba (pulverizador costal)'), (14, 'Matraca'), (15, 'Brete (vacinação gado)'), (16, 'Roçadeira'), (17, 'Motossera'), (18, 'Outros')], verbose_name='Bem produtivo')),
                ('outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bensProdutivos', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Bens produtivos disponíveis no lote',
                'verbose_name_plural': 'Bens produtivos disponíveis no lote',
            },
        ),
    ]
