# Generated by Django 2.0.4 on 2018-04-25 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_bemprodutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aplicacao_credito', models.IntegerField(choices=[(1, 'Apoio inicial (antes de 2015)'), (2, 'Apoio inicial I (após 2015)'), (3, 'Apoio inicial II (após 2015)'), (4, 'Fomento'), (5, 'Fomento Mulher'), (6, 'Moradia'), (7, 'PNHR-Minha Casa Minha Vida'), (8, 'Reforma Moradia'), (9, 'PNHR-Reforma')], verbose_name='Tipo de crédito')),
                ('outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoesCredito', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Com relação aos créditos, como está a aplicação no lote?',
                'verbose_name_plural': 'Com relação aos créditos, como está a aplicação no lote?',
            },
        ),
    ]
