# Generated by Django 2.0.4 on 2018-04-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_aplicacaocredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacaocredito',
            name='tipo_aplicacao_credito',
            field=models.IntegerField(choices=[(1, 'Apoio inicial (antes de 2015)'), (2, 'Apoio inicial I (após 2015)'), (3, 'Apoio inicial II (após 2015)'), (4, 'Fomento'), (5, 'Fomento Mulher'), (6, 'Moradia'), (7, 'PNHR-Minha Casa Minha Vida'), (8, 'Reforma Moradia'), (9, 'PNHR-Reforma'), (10, 'Não se aplica')], verbose_name='Tipo de crédito'),
        ),
        migrations.AlterField(
            model_name='bemprodutivo',
            name='bem_produtivo',
            field=models.IntegerField(choices=[(1, 'Trator'), (2, 'Caminhão'), (3, 'Caminhonete'), (4, 'Arado / grade'), (5, 'Plantadeira / adubadeira'), (6, 'Pulverizador "tratorizado"'), (7, 'Carroça ou carro de boi'), (8, 'Arado de tração animal'), (9, 'Triturador'), (10, 'Resfriador de leite'), (11, 'Cochos'), (12, 'Calcariadora'), (13, 'Bomba (pulverizador costal)'), (14, 'Matraca'), (15, 'Brete (vacinação gado)'), (16, 'Roçadeira'), (17, 'Motossera'), (18, 'Outros'), (19, 'Não se aplica')], verbose_name='Bem produtivo'),
        ),
        migrations.AlterField(
            model_name='beneficiosocial',
            name='tipo_beneficio',
            field=models.IntegerField(choices=[(1, 'Aposentadoria por tempo de serviço/idade'), (2, 'Aposentadoria por invalidez'), (3, 'Auxílio maternidade'), (4, 'Bolsa família'), (5, 'Bolsa verde'), (6, 'Outros'), (7, 'Não se aplica')], verbose_name='Qual documento o lote possui?'),
        ),
        migrations.AlterField(
            model_name='construcaolote',
            name='construcao_no_lote',
            field=models.IntegerField(choices=[(1, 'Galpão'), (2, 'Curral'), (3, 'Chiqueiro'), (4, 'Galinheiro'), (5, 'Segunda casa'), (6, 'Represa'), (7, 'Espaço para cultos religiosos'), (8, 'Estabelecimento comercial'), (9, 'Agroindústria'), (10, 'Outros'), (11, 'Não se aplica')], verbose_name='Construção'),
        ),
        migrations.AlterField(
            model_name='documentolote',
            name='tipo_documento',
            field=models.IntegerField(choices=[(1, 'Contrato de Assentamento'), (2, 'Contrato de Concessão de Uso - CCU'), (3, 'Título Definitivo - não registrado'), (4, 'Título Definitivo - registrado cartório'), (5, 'Matrícula da Propriedade'), (6, 'Não se aplica')], verbose_name='Qual documento o lote possui?'),
        ),
        migrations.AlterField(
            model_name='estruturaorganizativa',
            name='tipo_estrutura_organizativa',
            field=models.IntegerField(choices=[(1, 'Associação omunitária'), (2, 'Cooperativas (produção, créditos, etc.)'), (3, 'Associação ou grupos de mulheres'), (4, 'Núcleos de base ligados aos movimentos'), (5, 'Trabalhos coletivos (ajuda mútua) "multirões"'), (6, 'Grupos vinculados à igreja (pastoral, etc.)'), (7, 'Grupos de jovens'), (8, 'Grupos de saúde (pastoral, farmácia viva)'), (9, 'Associação de pais e mestres e outros'), (10, 'Grupos de laser e cultura'), (11, 'Não se aplica')], verbose_name='Estrutura organizativa'),
        ),
        migrations.AlterField(
            model_name='tratamentoagua',
            name='tratamento_agua',
            field=models.IntegerField(choices=[(1, 'Não há tratamento'), (2, 'Cloração'), (3, 'Fervura'), (4, 'Filtragem'), (5, 'Dessalinização'), (6, 'Outra'), (7, 'Não se aplica')], verbose_name='Forma de tratamento'),
        ),
    ]
