# Generated by Django 2.0.4 on 2018-04-25 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20180425_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoBancario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito_bancario', models.IntegerField(choices=[(1, 'Micro Crédito Produtivo (A)'), (2, 'A'), (3, 'A/C'), (4, 'Jovem'), (5, 'Mulher'), (6, 'Recuperação (Complementar)'), (7, 'Outros')], verbose_name='Tipo de crédito')),
                ('outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditosBancarios', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Com relação aos créditos bancários, como está a aplicação na parcela?',
                'verbose_name_plural': 'Com relação aos créditos bancários, como está a aplicação na parcela?',
            },
        ),
        migrations.RemoveField(
            model_name='aplicacaocredito',
            name='outros',
        ),
    ]
