# Generated by Django 2.0.4 on 2018-04-26 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180425_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducaoVegetal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.IntegerField(choices=[(1, 'Cultura'), (2, 'Olericultura'), (3, 'Fruticultura')], verbose_name='Classificação')),
                ('tipo_producao', models.IntegerField(verbose_name='Tipo de produção')),
                ('tipo_producao_outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de produção (Outros)')),
                ('area_plantada', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Área plantada')),
                ('medida_area_plantada', models.IntegerField(choices=[(1, 'ha'), (2, 'm2')], verbose_name='Medida da área plantada')),
                ('producao_consumo', models.FloatField(verbose_name='Produção (Consumo)')),
                ('producao_comercio', models.FloatField(verbose_name='Produção (Comércio)')),
                ('producao_unidade_medida', models.IntegerField(choices=[(1, 'Kg'), (2, 'un')], verbose_name='Unidade de medida da produção')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor (R$)')),
                ('irrigacao', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')], verbose_name='Plantio irrigado?')),
                ('area_irrigada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área irrigada')),
                ('medida_area_irrigada', models.IntegerField(choices=[(1, 'ha'), (2, 'm2')], verbose_name='Medida da área irrigada')),
                ('tipo_irrigacao', models.IntegerField(choices=[(1, 'Aspersão'), (2, 'Sulco'), (3, 'Gotejamento'), (4, 'Outros')], verbose_name='Tipo de irrigação')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoesVegetais', to='core.Lote', verbose_name='Lote')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
            ],
            options={
                'verbose_name': 'Produção Vegetal - Cultura',
                'verbose_name_plural': 'Produções Vegetais - Culturas',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.producaovegetal',),
        ),
        migrations.CreateModel(
            name='Fruticultura',
            fields=[
            ],
            options={
                'verbose_name': 'Produção Vegetal - Fruticultura',
                'verbose_name_plural': 'Produções Vegetais - Fruticulturas',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.producaovegetal',),
        ),
        migrations.CreateModel(
            name='Olericultura',
            fields=[
            ],
            options={
                'verbose_name': 'Produção Vegetal - Olericultura',
                'verbose_name_plural': 'Produções Vegetais - Olericulturas',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.producaovegetal',),
        ),
    ]
