# Generated by Django 2.0.4 on 2018-04-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cultura_fruticultura_olericultura_producaovegetal_tipoproducao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaovegetal',
            name='classificacao',
            field=models.IntegerField(verbose_name='Classificação'),
        ),
    ]
