# Generated by Django 2.0.4 on 2018-04-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20180425_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cultura',
        ),
        migrations.DeleteModel(
            name='Fruticultura',
        ),
        migrations.DeleteModel(
            name='Olericultura',
        ),
        migrations.AlterModelOptions(
            name='producaovegetal',
            options={'verbose_name': 'Produção Vegetal - (Cultura, Olericultura e Fruticultura)', 'verbose_name_plural': 'Produções Vegetais - (Cultura, Olericultura e Fruticultura)'},
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='classificacao',
            field=models.IntegerField(choices=[(1, 'Cultura'), (2, 'Olericultura'), (3, 'Fruticultura')], verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='irrigacao',
            field=models.IntegerField(blank=True, choices=[(1, 'Sim'), (2, 'Não')], null=True, verbose_name='Plantio irrigado?'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='medida_area_irrigada',
            field=models.IntegerField(blank=True, choices=[(1, 'ha'), (2, 'm2')], null=True, verbose_name='Medida da área irrigada'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='medida_area_plantada',
            field=models.IntegerField(choices=[(1, 'ha'), (2, 'm2')], verbose_name='Medida da área plantada'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='producao_comercio',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção (Comércio)'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='producao_consumo',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção (Consumo)'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='producao_unidade_medida',
            field=models.IntegerField(blank=True, choices=[(1, 'Kg'), (2, 'un')], null=True, verbose_name='Unidade de medida da produção'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='tipo_irrigacao',
            field=models.IntegerField(blank=True, choices=[(1, 'Aspersão'), (2, 'Sulco'), (3, 'Gotejamento'), (4, 'Outros')], null=True, verbose_name='Tipo de irrigação'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='tipo_producao',
            field=models.IntegerField(verbose_name='Tipo de produção'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Valor (R$)'),
        ),
    ]
