# Generated by Django 2.0.4 on 2018-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180426_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaovegetal',
            name='classificacao',
            field=models.IntegerField(verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='tipo_producao',
            field=models.IntegerField(choices=[(1, 'Amendoim'), (2, 'Arroz'), (3, 'Batata-doce'), (4, 'Cana-de-Açúcar'), (5, 'Feijão'), (6, 'Mamona'), (7, 'Mandioca de / Farinha'), (8, 'Mandioca de / Mesa'), (9, 'Milho'), (10, 'Alface'), (11, 'Cebolinha'), (12, 'Couve'), (13, 'Coentro'), (14, 'Couve-flor'), (15, 'Rabanete'), (16, 'Rúcula'), (17, 'Salsa'), (18, 'Abóbora'), (19, 'Maxixe'), (20, 'Melancia'), (21, 'Melão'), (22, 'Pepino'), (23, 'Pimentão'), (24, 'Quiabo'), (25, 'Tomate'), (26, 'Abacate'), (27, 'Acerola'), (28, 'Banana'), (29, 'Cajú'), (30, 'Côco'), (31, 'Goiaba'), (32, 'Jabuticaba'), (33, 'Jaca'), (34, 'Laranja'), (35, 'Lima'), (36, 'Limão'), (37, 'Manga'), (38, 'Maracujá'), (39, 'Tamarindo'), (40, 'Tangerina'), (41, 'Uva'), (99, 'Outros')], verbose_name='Tipo de produção'),
        ),
    ]
