# Generated by Django 2.0.4 on 2018-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180426_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaovegetal',
            name='classificacao',
            field=models.IntegerField(choices=[(1, 'Cultura'), (2, 'Olericultura'), (3, 'Fruticultura')], verbose_name='Classificação'),
        ),
    ]
