# Generated by Django 2.0.4 on 2018-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20180426_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
            ],
            options={
                'verbose_name': 'Produção Vegetal - Cultura',
                'verbose_name_plural': 'Produções Vegetais - Culturas',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.producaovegetal',),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='classificacao',
            field=models.IntegerField(verbose_name='Classificação'),
        ),
    ]
