# Generated by Django 2.0.4 on 2018-04-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180426_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olericultura',
            fields=[
            ],
            options={
                'verbose_name': 'Produção Vegetal - Olericultura',
                'verbose_name_plural': 'Produções Vegetais - Olericulturas',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.producaovegetal',),
        ),
    ]
