# Generated by Django 2.0.4 on 2018-04-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_olericultura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruticultura',
            fields=[
            ],
            options={
                'verbose_name': 'Produção Vegetal - Fruticultura',
                'verbose_name_plural': 'Produções Vegetais - Fruticulturas',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.producaovegetal',),
        ),
    ]
