# Generated by Django 2.0.4 on 2018-04-27 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20180427_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bovinocultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_criacao', models.IntegerField(choices=[(1, 'Gado Leiteiro'), (2, 'Gado de Corte')], verbose_name='Tipo de criação')),
                ('especificacao', models.IntegerField(choices=[(10, 'Touros'), (20, 'Vacas'), (30, 'Novilhas(os) + de 02 anos'), (40, 'Novilhas(os) + de 01 ano'), (50, 'Bezerras(os)'), (60, 'Boi')], verbose_name='Especificação')),
                ('quantidade_cabeças', models.IntegerField(verbose_name='Nº de Cabeça(s)')),
                ('valor_cabeca', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='R$/Cabeça')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoesAnimais', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Produção Animal - Bovinocultura (Efetivo Atual)',
            },
        ),
        migrations.DeleteModel(
            name='TipoProducao',
        ),
        migrations.AddField(
            model_name='producaovegetal',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='producaovegetal',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
