# Generated by Django 2.0.4 on 2018-04-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20180427_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducaoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.IntegerField(verbose_name='Classificação')),
                ('tipo_criacao', models.IntegerField(choices=[(1, 'Gado Leiteiro'), (2, 'Gado de Corte')], verbose_name='Tipo de criação')),
                ('especificacao', models.IntegerField(choices=[(10, 'Touros'), (20, 'Vacas'), (30, 'Novilhas(os) + de 02 anos'), (40, 'Novilhas(os) + de 01 ano'), (50, 'Bezerras(os)'), (60, 'Boi'), (70, 'Frango de corte caipira'), (80, 'Galinha caipira (somente frangos(as) e adultos)'), (90, 'Suínos'), (100, 'Ovinos'), (100, 'Equinos / Muares'), (120, 'Caprinos')], verbose_name='Especificação')),
                ('quantidade_cabeças', models.IntegerField(verbose_name='Nº de Cabeça(s)')),
                ('valor_cabeca', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='R$/Cabeça')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoesAnimais', to='core.Lote', verbose_name='Lote')),
            ],
        ),
        migrations.RemoveField(
            model_name='bovinocultura',
            name='lote',
        ),
        migrations.DeleteModel(
            name='Bovinocultura',
        ),
        migrations.CreateModel(
            name='OutraCriacao',
            fields=[
            ],
            options={
                'verbose_name': 'Produção Animal - Outras Criações Animais (Efetivo Atual)',
                'verbose_name_plural': 'Produção Animal - Outras Criações Animais (Efetivo Atual)',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.producaoanimal',),
        ),
        migrations.CreateModel(
            name='Bovinocultura',
            fields=[
            ],
            options={
                'verbose_name': 'Produção Animal - Bovinocultura (Efetivo Atual)',
                'verbose_name_plural': 'Produção Animal - Bovinocultura (Efetivo Atual)',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.producaoanimal',),
        ),
    ]
