# Generated by Django 2.0.4 on 2018-04-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20180427_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeExtrativista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacao', models.IntegerField(choices=[(1, 'Açaí(Kg)'), (2, 'Babaçu(Kg)'), (3, 'Buriti(Kg)'), (4, 'Cagaita(Kg)'), (5, 'Murici(Kg)'), (6, 'Pequi(Kg)'), (7, 'Outros')], verbose_name='Especificação')),
                ('outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros')),
                ('quantidade_frutos_ano', models.IntegerField(verbose_name='Quantidade Colhida / Ano - Fruto(s)')),
                ('quantidade_palmitos_ano', models.IntegerField(verbose_name='Quantidade Colhida / Ano - Palmito(s)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor R$/Kg')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividadesExtrativistas', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Atividade Extrativista',
                'verbose_name_plural': 'Atividades Extrativistas',
            },
        ),
        migrations.AlterModelOptions(
            name='producaovegetal',
            options={},
        ),
    ]
