# Generated by Django 2.0.4 on 2018-04-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180427_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducaoFlorestal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacao', models.IntegerField(choices=[(1, 'Eucalipto(m³)'), (2, 'Teca(m³)'), (3, 'Seringueira(Kg/látex)'), (4, 'Seringueira(m³/Madeira)'), (5, 'Outros')], verbose_name='Especificação')),
                ('outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros')),
                ('quantidade_produzida_ano', models.IntegerField(verbose_name='Quantidade Colhida / Ano - Fruto(s)')),
                ('area_plantada', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Área plantada (ha)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='R$/Unidade colhida')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoesFlorestais', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Produção Florestal',
                'verbose_name_plural': 'Produções Florestais',
            },
        ),
    ]
