# Generated by Django 2.0.4 on 2018-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_producaoflorestal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producaoanimal',
            name='area_capineira',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área capineira (ha)'),
        ),
        migrations.AddField(
            model_name='producaoanimal',
            name='area_pastagem_rotacionada',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área Pastejo Rotacionado (ha)'),
        ),
        migrations.AddField(
            model_name='producaoanimal',
            name='capineira',
            field=models.IntegerField(choices=[(10, 'Cana'), (20, 'Napier'), (99, 'Não se aplica')], default=0, verbose_name='Tipo de capineira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaoanimal',
            name='possui_capineira',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Possui Capineira?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaoanimal',
            name='possui_pastagem_rotacionada',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Possui Pastagem em Pastejo Rotacionado?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaoanimal',
            name='pratica_inseminacao_artificial',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Pratica inseminação artificial no rebanho leiteiro?'),
            preserve_default=False,
        ),
    ]
