# Generated by Django 2.0.4 on 2018-04-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20180427_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producaoanimal',
            name='area_capineira',
        ),
        migrations.RemoveField(
            model_name='producaoanimal',
            name='area_pastagem_rotacionada',
        ),
        migrations.RemoveField(
            model_name='producaoanimal',
            name='capineira',
        ),
        migrations.RemoveField(
            model_name='producaoanimal',
            name='possui_capineira',
        ),
        migrations.RemoveField(
            model_name='producaoanimal',
            name='possui_pastagem_rotacionada',
        ),
        migrations.RemoveField(
            model_name='producaoanimal',
            name='pratica_inseminacao_artificial',
        ),
    ]
