# Generated by Django 2.0.4 on 2018-04-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180427_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelTecnologicoProducaoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_capineira', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='Possui Capineira?')),
                ('tipo_capineira', models.IntegerField(choices=[(10, 'Cana'), (20, 'Napier'), (99, 'Não se aplica')], verbose_name='Tipo de Capineira')),
                ('possui_pastagem_rotacionada', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='Possui Pastagem em Pastejo Rotacionado?')),
                ('area_pastagem_rotacionada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área Pastejo Rotacionado (ha)')),
                ('patrica_insemincacao', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='Pratica inseminação artificial no rebanho leiteiro?')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveisTecnologicosProducaoAnimal', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Sobre o Nível Tecnológico da Produção Animal',
                'verbose_name_plural': 'Sobre o Nível Tecnológico da Produção Animal',
            },
        ),
    ]
