# Generated by Django 2.0.4 on 2018-04-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_niveltecnologicoproducaoanimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveltecnologicoproducaoanimal',
            name='id',
        ),
        migrations.AlterField(
            model_name='niveltecnologicoproducaoanimal',
            name='lote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='niveisTecnologicosProducaoAnimal', serialize=False, to='core.Lote', verbose_name='Lote'),
        ),
    ]
