# Generated by Django 2.0.4 on 2018-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20180427_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='area_preservacao_permanente',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Existe Área de Preservação Permanente (APP) dentro do seu lote/parcela?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='area_preservacao_permanente_cercada',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='A Área de Preservação Permanente está cercada ou isolada?'),
            preserve_default=False,
        ),
    ]
