# Generated by Django 2.0.4 on 2018-04-27 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20180427_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveltecnologicoproducaoanimal',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='niveltecnologicoproducaoanimal',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
