# Generated by Django 2.0.4 on 2018-04-27 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20180427_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveltecnologicoproducaoanimal',
            name='lote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nivelTecnologicoProducaoAnimal', serialize=False, to='core.Lote', verbose_name='Lote'),
        ),
    ]
