# Generated by Django 2.0.4 on 2018-04-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20180427_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaAmbiental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.IntegerField(choices=[(10, 'Erosão (laminar, sulco, voçoroca)'), (20, 'Compactação do solo'), (30, 'Contaminação por uso de  agrotóxicos/destinação inadequada de embalagens'), (40, 'Exposição de lixo de forma inadequada (a céu aberto)'), (50, 'Queima de lixo'), (60, 'Destinação inadequada de pilhas/baterias/lixo eletrônico'), (70, 'Poluição/contaminação nascente e/ou rios/córregos'), (80, 'Assoreamento de rio/córrego'), (90, 'Queimadas'), (100, 'Desmatamento'), (110, 'Outros')], verbose_name='Tipo de problema')),
                ('outros', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outros (Especificar)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemasAmbientais', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Quais são os problemas ambientais existentes no lote?',
                'verbose_name_plural': 'Quais são os problemas ambientais existentes no lote?',
            },
        ),
    ]
