# Generated by Django 2.0.4 on 2018-04-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_problemaambiental'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraticaConservacionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pratica', models.IntegerField(choices=[(10, 'Adubação verde'), (20, 'Curvas em nível'), (30, 'Rotação/consórcio de culturas'), (40, 'Adubação orgânica'), (50, 'Cordões de vegetação em nível'), (60, 'Controle alternativo de pragas e doenças'), (70, 'Agrofloresta'), (80, 'Plantios de árvores para proteção de mananciais / áreas degradadas')], verbose_name='Prática Conservacionista')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praticasConservacionistas', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Quais são as práticas conservacionistas praticadas na propriedade?',
                'verbose_name_plural': 'Quais são as práticas conservacionistas praticadas na propriedade?',
            },
        ),
        migrations.AlterField(
            model_name='problemaambiental',
            name='tipo_problema',
            field=models.IntegerField(choices=[(1, 'Erosão (laminar, sulco, voçoroca)'), (2, 'Compactação do solo'), (3, 'Contaminação por uso de  agrotóxicos/destinação inadequada de embalagens'), (4, 'Exposição de lixo de forma inadequada (a céu aberto)'), (5, 'Queima de lixo'), (6, 'Destinação inadequada de pilhas/baterias/lixo eletrônico'), (7, 'Poluição/contaminação nascente e/ou rios/córregos'), (8, 'Assoreamento de rio/córrego'), (9, 'Queimadas'), (10, 'Desmatamento'), (11, 'Outros')], verbose_name='Tipo de problema'),
        ),
    ]
