# Generated by Django 2.0.4 on 2018-04-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_destinolixodomestico_destinomaterialorganico'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenciamentoAmbiental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.IntegerField(choices=[(1, 'Agropecuária'), (2, 'Irrigação'), (3, 'Aquicultura'), (4, 'Lazer e Turismo'), (5, 'Outros')], verbose_name='Tipo de atividade')),
                ('outros', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outros (Especificar)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenciamentosAmbientais', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Necessita de licenciamento ambiental para alguma atividade?',
                'verbose_name_plural': 'Necessita de licenciamento ambiental para alguma atividade?',
            },
        ),
        migrations.AlterModelOptions(
            name='destinomaterialorganico',
            options={'verbose_name': 'Qual o destino do material orgânico?', 'verbose_name_plural': 'Qual o destino do material orgânico?'},
        ),
    ]
