# Generated by Django 2.0.4 on 2018-04-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_lote_necessita_licenciamento_ambiental'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoSaude',
            fields=[
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='atendimentosSaude', serialize=False, to='core.Lote', verbose_name='Lote')),
                ('hospital', models.IntegerField(choices=[(1, 'P.A'), (2, 'Cidade')], verbose_name='Local de atendimento')),
                ('posto_saude', models.IntegerField(choices=[(1, 'P.A'), (2, 'Cidade')], verbose_name='Local de atendimento')),
                ('farmacia', models.IntegerField(choices=[(1, 'P.A'), (2, 'Cidade')], verbose_name='Local de atendimento')),
                ('outros', models.IntegerField(choices=[(1, 'P.A'), (2, 'Cidade')], verbose_name='Local de atendimento')),
                ('outros_especificacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outros (Especificar)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Onde é feito o atendimento à saúde para as famílias do assentamento?',
                'verbose_name_plural': 'Onde é feito o atendimento à saúde para as famílias do assentamento?',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='necessita_autoriacao_exploracao_florestal_queima_controlada',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Necessita de autorização de exploração florestal e/ou queima controlada?'),
            preserve_default=False,
        ),
    ]
