# Generated by Django 2.0.4 on 2018-04-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20180427_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentosaude',
            name='farmacia',
            field=models.IntegerField(choices=[(1, 'P.A'), (2, 'Cidade')], verbose_name='Farmácia'),
        ),
        migrations.AlterField(
            model_name='atendimentosaude',
            name='hospital',
            field=models.IntegerField(choices=[(1, 'P.A'), (2, 'Cidade')], verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='atendimentosaude',
            name='outros',
            field=models.IntegerField(blank=True, choices=[(1, 'P.A'), (2, 'Cidade')], null=True, verbose_name='Outros'),
        ),
        migrations.AlterField(
            model_name='atendimentosaude',
            name='posto_saude',
            field=models.IntegerField(choices=[(1, 'P.A'), (2, 'Cidade')], verbose_name='Posto de saúde'),
        ),
    ]
