# Generated by Django 2.0.4 on 2018-04-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20180427_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_saude', models.IntegerField(choices=[(10, 'Programa Saúde da Família - PSF'), (20, 'Agentes Comunitários de Saúde'), (30, 'Atendimento médico'), (40, 'Atendimento odontológico'), (50, 'Campanha de vacinação'), (60, 'Saúde da Mulher')], verbose_name='Programa/Tipo de atendimento à saúde')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programasSaude', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Qual o programa ou tipo de atendimento à saúde são disponibilizado no P.A?',
                'verbose_name_plural': 'Quais os programas ou tipos de atendimento à saúde são disponibilizados no P.A?',
            },
        ),
    ]
