# Generated by Django 2.0.4 on 2018-04-30 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_programasaude'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade_fisica', models.IntegerField(choices=[(1, 'Futebol'), (2, 'Caminhada/corrida'), (3, 'Nenhuma atividade física'), (4, 'Outros')], verbose_name='Esporte/atividade física')),
                ('outros', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outros (Especificar)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Esporte/atividade física praticada',
                'verbose_name_plural': 'Quais são os esportes/atividades físicas praticados pelos familiares com maior frequência?',
            },
        ),
        migrations.AlterModelOptions(
            name='aplicacaocredito',
            options={'verbose_name': 'Aplicação do crédito no lote', 'verbose_name_plural': 'Com relação aos créditos, como está a aplicação no lote?'},
        ),
        migrations.AlterModelOptions(
            name='atendimentosaude',
            options={'verbose_name': 'Local de atendimento à saúde', 'verbose_name_plural': 'Onde é feito o atendimento à saúde para as famílias do assentamento?'},
        ),
        migrations.AlterModelOptions(
            name='bemprodutivo',
            options={'verbose_name': 'Bem produtivo', 'verbose_name_plural': 'Bens produtivos disponíveis no lote'},
        ),
        migrations.AlterModelOptions(
            name='beneficiosocial',
            options={'verbose_name': 'Tipo de benefício', 'verbose_name_plural': 'Quais os tipos de benefício?'},
        ),
        migrations.AlterModelOptions(
            name='construcaolote',
            options={'verbose_name': 'Contruído no lote', 'verbose_name_plural': 'O que tem construído no lote?'},
        ),
        migrations.AlterModelOptions(
            name='creditobancario',
            options={'verbose_name': 'Aplicação do crédito bancário na parcela', 'verbose_name_plural': 'Com relação aos créditos bancários, como está a aplicação na parcela?'},
        ),
        migrations.AlterModelOptions(
            name='destinolixodomestico',
            options={'verbose_name': 'Destino do lixo doméstico não orgânico?', 'verbose_name_plural': 'Qual é o destino do lixo doméstico não orgânico?'},
        ),
        migrations.AlterModelOptions(
            name='destinomaterialorganico',
            options={'verbose_name': 'Destino do material orgânico?', 'verbose_name_plural': 'Qual o destino do material orgânico?'},
        ),
        migrations.AlterModelOptions(
            name='documentolote',
            options={'verbose_name': 'Documento do lote', 'verbose_name_plural': 'Quais documentos o lote possui?'},
        ),
        migrations.AlterModelOptions(
            name='estruturaorganizativa',
            options={'verbose_name': 'Estruturas organizativa interna existente', 'verbose_name_plural': 'Das estruturas organizativas internas ao assentamento diga qual existe no assentamento e de quais os membros da família participam'},
        ),
        migrations.AlterModelOptions(
            name='fonteagua',
            options={'verbose_name': 'Abastecimento de água', 'verbose_name_plural': 'De onde vem a água que abastece a família?'},
        ),
        migrations.AlterModelOptions(
            name='licenciamentoambiental',
            options={'verbose_name': 'Licenciamento ambiental', 'verbose_name_plural': 'Necessita de licenciamento ambiental para alguma atividade?'},
        ),
        migrations.AlterModelOptions(
            name='praticaconservacionista',
            options={'verbose_name': 'Prática conservacionista praticada', 'verbose_name_plural': 'Quais são as práticas conservacionistas praticadas na propriedade?'},
        ),
        migrations.AlterModelOptions(
            name='problemaambiental',
            options={'verbose_name': 'Problema ambiental', 'verbose_name_plural': 'Quais são os problemas ambientais existentes no lote?'},
        ),
        migrations.AlterModelOptions(
            name='programasaude',
            options={'verbose_name': 'Programa ou tipo de atendimento à saúde disponibilizado no P.A', 'verbose_name_plural': 'Quais programas ou tipos de atendimento à saúde são disponibilizados no P.A?'},
        ),
        migrations.AlterModelOptions(
            name='tratamentoagua',
            options={'verbose_name': 'Tratamento da água', 'verbose_name_plural': 'Qual a forma tratamento da água para consumo?'},
        ),
        migrations.AddField(
            model_name='lote',
            name='qualidade_servico_saude',
            field=models.IntegerField(choices=[(1, 'Ótimo'), (2, 'Bom'), (3, 'Ruim'), (4, 'Péssimo')], default=0, verbose_name='Como os moradores consideram o serviço de saúde no assentamento?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentolote',
            name='tipo_documento',
            field=models.IntegerField(choices=[(1, 'Contrato de Assentamento'), (2, 'Contrato de Concessão de Uso - CCU'), (3, 'Título Definitivo - não registrado'), (4, 'Título Definitivo - registrado cartório'), (5, 'Matrícula da Propriedade')], verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='atividadefisica',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividadesFisicas', to='core.Lote', verbose_name='Lote'),
        ),
    ]
