# Generated by Django 2.0.4 on 2018-04-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20180430_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaAtividadeFisica',
            fields=[
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='frequenciasAtividadesFisicas', serialize=False, to='core.Lote', verbose_name='Lote')),
                ('frequencia_atividade_fisica', models.IntegerField(choices=[(1, 'Diariamente'), (2, 'Duas vezes por semana'), (3, 'Mais de duas vezes por semana')], verbose_name='Frequência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Frequência praticada',
                'verbose_name_plural': 'Com que frequência praticam atividades físicas ou esporte?',
            },
        ),
    ]
