# Generated by Django 2.0.4 on 2018-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_frequenciaatividadefisica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequenciaatividadefisica',
            name='lote',
        ),
        migrations.AddField(
            model_name='lote',
            name='frequencia_atividade_fisica',
            field=models.IntegerField(choices=[(1, 'Diariamente'), (2, 'Duas vezes por semana'), (3, 'Mais de duas vezes por semana'), (4, 'Não pratica')], default=0, verbose_name='Com que frequência praticam atividades físicas ou esportes?'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FrequenciaAtividadeFisica',
        ),
    ]
