# Generated by Django 2.0.4 on 2018-04-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_espacodisponivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstabelecimentoEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento_ensino', models.IntegerField(choices=[(1, 'Pré-escolar (creche)'), (2, 'Ensino Fundamental'), (3, 'EJA'), (4, 'Ensino Médio'), (5, 'Ensino Superior'), (6, 'Ensino Profissionalizante'), (7, 'Não há estabelecimento de ensino no PA')], verbose_name='Estabelecimento de ensino')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentosEnsino', to='core.Lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Estabelecimento de ensino disponível no assentamento',
                'verbose_name_plural': 'Que tipo de estabelecimento de ensino está disponível no assentamento?',
            },
        ),
    ]
