# Generated by Django 2.0.4 on 2018-04-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_estabelecimentoensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='oferta_transporte_interno',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Para a escola do assentamento há oferta de transporte interno?'),
            preserve_default=False,
        ),
    ]
