# Generated by Django 2.0.4 on 2018-05-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20180503_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='coordenada_x',
            field=models.CharField(max_length=30, verbose_name='Coordenada "X"'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='coordenada_y',
            field=models.CharField(max_length=30, verbose_name='Coordenada "Y"'),
        ),
    ]
