# Generated by Django 2.0.4 on 2018-05-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20180503_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonteagua',
            name='outra',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Outra (Especificar)'),
        ),
    ]
