# Generated by Django 2.0.4 on 2018-05-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_fonteagua_outra'),
    ]

    operations = [
        migrations.AddField(
            model_name='construcaolote',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
