# Generated by Django 2.0.4 on 2018-05-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_bemprodutivo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacaocredito',
            name='valor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Valor (R$)'),
            preserve_default=False,
        ),
    ]
