# Generated by Django 2.0.4 on 2018-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20180503_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditobancario',
            name='adimplente',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Adimplente?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditobancario',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor (R$)'),
            preserve_default=False,
        ),
    ]
