# Generated by Django 2.0.4 on 2018-05-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_produtoorigemanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveltecnologicoproducaoanimal',
            name='area_capineira',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área da capineira (ha)'),
        ),
    ]
