# Generated by Django 2.0.4 on 2018-05-03 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_niveltecnologicoproducaoanimal_area_capineira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.IntegerField(verbose_name='Classificação')),
                ('especificacao', models.IntegerField(choices=[(1, 'Carne(Kg)'), (2, 'Leite(L)'), (3, 'Mel(Kg)'), (4, 'Ovos(Dz)'), (5, 'Peixes(Kg)'), (6, 'Outros')], verbose_name='Especificação')),
                ('outros', models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros (Especificar)')),
                ('producao_consumo', models.IntegerField(verbose_name='Produção (Consumo)')),
                ('producao_comercio', models.IntegerField(verbose_name='Produção (Comércio)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor R$/Unidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtosOrigemAnimal', to='core.Lote', verbose_name='Lote')),
            ],
        ),
        migrations.RemoveField(
            model_name='produtoorigemanimal',
            name='lote',
        ),
        migrations.DeleteModel(
            name='ProdutoOrigemAnimal',
        ),
        migrations.CreateModel(
            name='OrigemAnimal',
            fields=[
            ],
            options={
                'verbose_name': 'Produto de origem animal produzido',
                'verbose_name_plural': 'Sobre os produtos de origem animal produzidos no último ano agrícola',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.produto',),
        ),
        migrations.CreateModel(
            name='ProcessadoBeneficiado',
            fields=[
            ],
            options={
                'verbose_name': 'Produto processado ou beneficiado',
                'verbose_name_plural': 'Sobre os produtos processados ou beneficiados no estabelecimento, no último ano agrícola (agroindústria)',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.produto',),
        ),
    ]
