# Generated by Django 2.0.4 on 2018-05-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20180503_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='especificacao',
            field=models.IntegerField(choices=[(1, 'Carne(Kg)'), (2, 'Leite(L)'), (3, 'Mel(Kg)'), (4, 'Ovos(Dz)'), (5, 'Peixes(Kg)'), (6, 'Banha(Kg)'), (7, 'Conservas(Un)'), (8, 'Doces(Un)'), (9, 'Farinha de Mandioca(Kg)'), (10, 'Linguiça(Kg)'), (11, 'Povilho de Mandioca(Kg)'), (12, 'Queijo(Kg)'), (13, 'Rapadura(Kg)'), (14, 'Outros')], verbose_name='Especificação'),
        ),
    ]
