# Generated by Django 2.0.4 on 2018-05-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20180504_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemprodutivo',
            name='bem_produtivo',
            field=models.IntegerField(choices=[(1, 'Trator'), (2, 'Caminhão'), (3, 'Caminhonete'), (4, 'Arado / grade'), (5, 'Plantadeira / adubadeira'), (6, 'Pulverizador "tratorizado"'), (7, 'Carroça ou carro de boi'), (8, 'Arado de tração animal'), (9, 'Triturador'), (10, 'Resfriador de leite'), (11, 'Cochos'), (12, 'Calcariadora'), (13, 'Bomba (pulverizador costal)'), (14, 'Matraca'), (15, 'Brete (vacinação gado)'), (16, 'Roçadeira'), (17, 'Motosserra'), (18, 'Outros')], verbose_name='Bem produtivo'),
        ),
        migrations.AlterField(
            model_name='estruturaorganizativa',
            name='tipo_estrutura_organizativa',
            field=models.IntegerField(choices=[(1, 'Associação comunitária'), (2, 'Cooperativas (produção, créditos, etc.)'), (3, 'Associação ou grupos de mulheres'), (4, 'Núcleos de base ligados aos movimentos'), (5, 'Trabalhos coletivos (ajuda mútua) "multirões"'), (6, 'Grupos vinculados à igreja (pastoral, etc.)'), (7, 'Grupos de jovens'), (8, 'Grupos de saúde (pastoral, farmácia viva)'), (9, 'Associação de pais e mestres e outros'), (10, 'Grupos de laser e cultura')], verbose_name='Estrutura organizativa'),
        ),
        migrations.AlterField(
            model_name='producaoanimal',
            name='especificacao',
            field=models.IntegerField(choices=[(10, 'Touros'), (20, 'Vacas'), (30, 'Novilhas(os) + de 02 anos'), (40, 'Novilhas(os) + de 01 ano'), (50, 'Bezerras(os)'), (60, 'Boi'), (70, 'Frango de corte caipira'), (80, 'Galinha caipira (somente frangos(as) e adultos)'), (90, 'Suínos'), (100, 'Ovinos'), (110, 'Equinos / Muares'), (120, 'Caprinos')], verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='irrigacao',
            field=models.IntegerField(blank=True, choices=[(1, 'Sim'), (0, 'Não')], null=True, verbose_name='Plantio irrigado?'),
        ),
    ]
