# Generated by Django 2.0.4 on 2018-05-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20180505_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='desativado_por',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='pessoas',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='membro',
            name='cpf',
            field=models.CharField(default='', max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='estuda',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Estuda?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='idade',
            field=models.IntegerField(default=0, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='parentesco',
            field=models.IntegerField(choices=[(1, 'Cônjuge'), (2, 'Titular'), (1, 'Irmão(a)'), (1, 'Tio(a)'), (1, 'Primo(a)'), (1, 'Filho(a)'), (1, 'Cunhado(a)')], default=0, verbose_name='Parentesco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.Familia', verbose_name='Familia'),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
