# Generated by Django 2.0.4 on 2018-05-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20180505_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='escolaridade',
            field=models.IntegerField(choices=[(1, 'Não alfabetizado'), (2, '1º ao 4º ano'), (3, '5º ao 9º ano'), (4, 'Fundamental completo'), (5, 'EJA - Educação de Jovens e Adultos'), (6, 'Médio incompleto'), (7, 'Médio completo'), (8, 'Superior incompleto'), (9, 'Superior completo'), (10, 'Pós Graduação incompleto'), (11, 'Pós Graduação completo')], default=0, verbose_name='Escolaridade'),
            preserve_default=False,
        ),
    ]
