# Generated by Django 2.0.4 on 2018-05-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_membro_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='parentesco',
            field=models.IntegerField(choices=[(1, 'Cônjuge'), (2, 'Titular'), (1, 'Irmão(a)'), (1, 'Tio(a)'), (1, 'Primo(a)'), (1, 'Filho(a)'), (1, 'Cunhado(a)'), (8, 'Genro/Nora')], verbose_name='Parentesco'),
        ),
    ]
