# Generated by Django 2.0.4 on 2018-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20180505_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='parentesco',
            field=models.IntegerField(choices=[(1, 'Cônjuge'), (2, 'Titular'), (1, 'Irmão(a)'), (1, 'Tio(a)'), (1, 'Primo(a)'), (1, 'Filho(a)'), (1, 'Cunhado(a)'), (8, 'Genro/Nora'), (9, 'Neto(a)')], verbose_name='Parentesco'),
        ),
    ]
