# Generated by Django 2.0.4 on 2018-05-05 21:49

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0085_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendaTrabalhoForaLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('quantidade_dias_ano', models.IntegerField(verbose_name='Quantidade de dias/ano trabalha fora do lote')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor da Diária (R$/dia)')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_rendatrabalhoforalote_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_rendatrabalhoforalote_desativado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='membro',
            name='trabalho_antes_do_lote',
            field=models.IntegerField(blank=True, choices=[(1, 'Sempre trabalhou no campo'), (2, 'Trabalhou parte do tempo na cidade'), (3, 'Nunca trabalhou no campo antes')], null=True, verbose_name='Antes de entrar no lote, trabalhava onde?'),
        ),
        migrations.AddField(
            model_name='rendatrabalhoforalote',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendas_fora_do_lote', to='core.Membro', verbose_name='Membro'),
        ),
        migrations.AddField(
            model_name='rendatrabalhoforalote',
            name='modificado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_rendatrabalhoforalote_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
