# Generated by Django 2.0.4 on 2018-05-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20180505_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendatrabalhoforalote',
            name='id',
        ),
        migrations.AlterField(
            model_name='rendatrabalhoforalote',
            name='membro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rendas_fora_do_lote', serialize=False, to='core.Membro', verbose_name='Membro'),
        ),
    ]
