# Generated by Django 2.0.4 on 2018-05-05 22:02

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0087_auto_20180505_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoFrequente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('uso_frequente', models.IntegerField(choices=[(1, 'Bebidas alcoólicas'), (2, 'Cigarros'), (3, 'Remédios de alto custo'), (4, 'Outros')], verbose_name='Selecione')),
                ('outros', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outros (Especificar)')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_usofrequente_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_usofrequente_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_frequentes', to='core.Membro', verbose_name='Membro')),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_usofrequente_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faz o uso frequente de',
                'verbose_name_plural': 'Quais os tipos de usos frequentes?',
            },
        ),
    ]
