# Generated by Django 2.0.4 on 2018-05-05 22:12

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0088_usofrequente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoEnsinoUtilizada',
            fields=[
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('membro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='opcao_ensino_utilizada', serialize=False, to='core.Membro', verbose_name='Membro')),
                ('opcao_ensino', models.IntegerField(choices=[(1, 'Frequenta escola em outro assentamento'), (2, 'Frequenta escola na cidade mais próxima'), (3, 'Deixa de frequentar a escola'), (4, 'Outros')], verbose_name='Selecione')),
                ('outros', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outros (Especificar)')),
                ('distancia_percorrida', models.IntegerField(verbose_name='Distância até a escola (Km)')),
                ('oferta_de_transporte', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='Há oferta de transporte para a escola?')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_opcaoensinoutilizada_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_opcaoensinoutilizada_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_opcaoensinoutilizada_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opção de ensino utilizada',
                'verbose_name_plural': 'Quais as opções de ensino utilizadas pelo membro?',
            },
        ),
        migrations.AlterModelOptions(
            name='rendatrabalhoforalote',
            options={'verbose_name': 'Renda de trabalho fora do lote', 'verbose_name_plural': 'Sobre a renda de trabalho fora do lote'},
        ),
        migrations.AlterField(
            model_name='rendatrabalhoforalote',
            name='membro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='renda_trabalho_fora_lote', serialize=False, to='core.Membro', verbose_name='Membro'),
        ),
    ]
