# Generated by Django 2.0.4 on 2018-05-05 22:33

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0089_auto_20180505_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaoPossuiDocumento',
            fields=[
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nao_possui_documento', serialize=False, to='core.Lote', verbose_name='Lote')),
                ('certidao_nascimento', models.IntegerField(verbose_name='Certidão de Nascimento')),
                ('identidade', models.IntegerField(verbose_name='Identidade (RG) - a partir de 12 anos')),
                ('cpf', models.IntegerField(verbose_name='Cadastro de Pessoa Física (CPF)')),
                ('carteira_de_trabalho', models.IntegerField(verbose_name='Carteira de Trabalho (CTPS) - a partir de 14 anos')),
                ('certidao_de_casamento_ou_uniao_estavel', models.IntegerField(verbose_name='Certidão de Casamento ou União Estável')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_naopossuidocumento_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_naopossuidocumento_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_naopossuidocumento_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Com relação à documentação, quantas pessoas NÃO POSSUEM os documentos relacionados abaixo?',
                'verbose_name_plural': 'Com relação à documentação, quantas pessoas NÃO POSSUEM os documentos relacionados abaixo?',
            },
        ),
        migrations.AlterModelOptions(
            name='opcaoensinoutilizada',
            options={'verbose_name': 'Opção de ensino utilizada:', 'verbose_name_plural': 'Quais as opções de ensino utilizadas pelo membro?'},
        ),
    ]
