# Generated by Django 2.0.4 on 2018-05-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20180505_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='necessita_licenciamento_ambiental',
            field=models.IntegerField(verbose_name='Necessita de licenciamento ambiental de atividade?'),
        ),
    ]
