# Generated by Django 2.0.4 on 2018-05-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20180508_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='necessita_licenciamento_ambiental',
            field=models.IntegerField(default=0, verbose_name='Necessita de licenciamento ambiental de atividade?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='oferta_transporte_interno',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não'), (99, 'Não se aplica')], verbose_name='Para a escola do assentamento há oferta de transporte interno?'),
        ),
    ]
