# Generated by Django 2.0.4 on 2018-05-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20180514_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaoanimal',
            name='especificacao',
            field=models.IntegerField(choices=[(10, 'Touros'), (20, 'Vacas'), (30, 'Novilhas(os) + de 02 anos'), (40, 'Novilhas(os) + de 01 ano'), (50, 'Bezerras(os)'), (60, 'Boi'), (70, 'Frango de corte caipira'), (80, 'Galinha caipira (somente frangos(as) e adultos)'), (90, 'Suínos'), (100, 'Ovinos'), (110, 'Equinos / Muares'), (120, 'Caprinos'), (99, 'Outros')], verbose_name='Especificação'),
        ),
    ]
