# Generated by Django 2.0.4 on 2018-05-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20180514_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='possui_capineira',
            field=models.IntegerField(default=0, verbose_name='Possui Capineira?'),
        ),
    ]
