# Generated by Django 2.0.4 on 2018-05-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_remove_niveltecnologicoproducaoanimal_possui_capineira'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeextrativista',
            name='canal_comercializacao',
            field=models.IntegerField(blank=True, choices=[(10, 'Venda direta ao consumidor (de casa em casa)'), (20, 'Venda em feiras'), (30, 'Entrega para supermercados, mercearias, açougues, etc'), (40, 'Venda p/ indústrias, e/ou agroindústrias (laticínios etc'), (50, 'Venda para agentes "atravessadores"'), (60, 'Outros')], null=True, verbose_name='Formas/Canais de Comercialização'),
        ),
        migrations.AddField(
            model_name='atividadeextrativista',
            name='mercado_institucional',
            field=models.IntegerField(blank=True, choices=[(10, 'PAA-CONAB'), (20, 'PAA-Prefeitura / MDS'), (30, 'Alimentação Escolar - PNAE'), (40, 'Biodiesel'), (50, 'Outros')], null=True, verbose_name='Mercado Institucional'),
        ),
        migrations.AddField(
            model_name='producaoflorestal',
            name='canal_comercializacao',
            field=models.IntegerField(blank=True, choices=[(10, 'Venda direta ao consumidor (de casa em casa)'), (20, 'Venda em feiras'), (30, 'Entrega para supermercados, mercearias, açougues, etc'), (40, 'Venda p/ indústrias, e/ou agroindústrias (laticínios etc'), (50, 'Venda para agentes "atravessadores"'), (60, 'Outros')], null=True, verbose_name='Formas/Canais de Comercialização'),
        ),
        migrations.AddField(
            model_name='producaovegetal',
            name='canal_comercializacao',
            field=models.IntegerField(blank=True, choices=[(10, 'Venda direta ao consumidor (de casa em casa)'), (20, 'Venda em feiras'), (30, 'Entrega para supermercados, mercearias, açougues, etc'), (40, 'Venda p/ indústrias, e/ou agroindústrias (laticínios etc'), (50, 'Venda para agentes "atravessadores"'), (60, 'Outros')], null=True, verbose_name='Formas/Canais de Comercialização'),
        ),
        migrations.AddField(
            model_name='producaovegetal',
            name='mercado_institucional',
            field=models.IntegerField(blank=True, choices=[(10, 'PAA-CONAB'), (20, 'PAA-Prefeitura / MDS'), (30, 'Alimentação Escolar - PNAE'), (40, 'Biodiesel'), (50, 'Outros')], null=True, verbose_name='Mercado Institucional'),
        ),
        migrations.AddField(
            model_name='produto',
            name='canal_comercializacao',
            field=models.IntegerField(blank=True, choices=[(10, 'Venda direta ao consumidor (de casa em casa)'), (20, 'Venda em feiras'), (30, 'Entrega para supermercados, mercearias, açougues, etc'), (40, 'Venda p/ indústrias, e/ou agroindústrias (laticínios etc'), (50, 'Venda para agentes "atravessadores"'), (60, 'Outros')], null=True, verbose_name='Formas/Canais de Comercialização'),
        ),
        migrations.AddField(
            model_name='produto',
            name='mercado_institucional',
            field=models.IntegerField(blank=True, choices=[(10, 'PAA-CONAB'), (20, 'PAA-Prefeitura / MDS'), (30, 'Alimentação Escolar - PNAE'), (40, 'Biodiesel'), (50, 'Outros')], null=True, verbose_name='Mercado Institucional'),
        ),
        migrations.AlterField(
            model_name='descarteanimal',
            name='canal_comercializacao',
            field=models.IntegerField(choices=[(10, 'Venda para outro produtor'), (20, 'Entrega para frigorífico/açougue'), (30, 'Venda para agentes "atravessadores"'), (40, 'Outros')], verbose_name='Formas/Canais de Comercialização'),
        ),
    ]
