# Generated by Django 2.0.4 on 2018-05-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20180514_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='parentesco',
            field=models.IntegerField(blank=True, choices=[(10, 'Cônjuge'), (20, 'Titular'), (10, 'Irmão(a)'), (10, 'Tio(a)'), (10, 'Primo(a)'), (10, 'Filho(a)'), (10, 'Cunhado(a)'), (80, 'Genro/Nora'), (90, 'Neto(a)')], null=True, verbose_name='Parentesco'),
        ),
    ]
