# Generated by Django 2.0.4 on 2018-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_auto_20180514_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naopossuidocumento',
            name='carteira_de_trabalho',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carteira de Trabalho (CTPS) - a partir de 14 anos'),
        ),
        migrations.AlterField(
            model_name='naopossuidocumento',
            name='certidao_de_casamento_ou_uniao_estavel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Certidão de Casamento ou União Estável'),
        ),
        migrations.AlterField(
            model_name='naopossuidocumento',
            name='certidao_nascimento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Certidão de Nascimento'),
        ),
        migrations.AlterField(
            model_name='naopossuidocumento',
            name='cpf',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cadastro de Pessoa Física (CPF)'),
        ),
        migrations.AlterField(
            model_name='naopossuidocumento',
            name='identidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Identidade (RG) - a partir de 12 anos'),
        ),
    ]
