# Generated by Django 2.0.4 on 2018-05-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20180514_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveltecnologicoproducaoanimal',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='niveltecnologicoproducaoanimal',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveisTecnologicosProducaoAnimal', to='core.Lote', verbose_name='Lote'),
        ),
    ]
