# Generated by Django 2.0.4 on 2018-05-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20180514_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveltecnologicoproducaoanimal',
            name='area_pastagem_rotacionada',
        ),
        migrations.RemoveField(
            model_name='niveltecnologicoproducaoanimal',
            name='patrica_insemincacao',
        ),
        migrations.RemoveField(
            model_name='niveltecnologicoproducaoanimal',
            name='possui_pastagem_rotacionada',
        ),
        migrations.AddField(
            model_name='lote',
            name='area_pastejo_rotacionado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tamanho da área em sistema de Pastejo Rotacionado'),
        ),
        migrations.AddField(
            model_name='lote',
            name='possui_pastagem_em_pastejo_rotacionado',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Possui Pastagem em Pastejo Rotacionado?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='pratica_inseminacao_artificial_no_rebanho_leiteiro',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Pratica inseminação aritificial no rebanho leiteiro?'),
            preserve_default=False,
        ),
    ]
