# Generated by Django 2.0.4 on 2018-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20180514_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='data_homologacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Homologação'),
        ),
    ]
