# Generated by Django 2.0.4 on 2018-05-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_lote_data_homologacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='parentesco',
            field=models.IntegerField(choices=[(10, 'Titular'), (20, 'Cônjuge'), (20, 'Irmão(a)'), (20, 'Tio(a)'), (20, 'Primo(a)'), (20, 'Filho(a)'), (20, 'Cunhado(a)'), (80, 'Genro/Nora'), (90, 'Neto(a)'), (100, 'Agregado(a)')], default=0, verbose_name='Parentesco'),
            preserve_default=False,
        ),
    ]
