# Generated by Django 2.0.4 on 2018-05-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20180515_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='parentesco',
            field=models.IntegerField(choices=[(10, 'Titular'), (20, 'Cônjuge'), (30, 'Irmão(a)'), (40, 'Tio(a)'), (50, 'Primo(a)'), (60, 'Filho(a)'), (70, 'Cunhado(a)'), (80, 'Genro/Nora'), (90, 'Neto(a)'), (100, 'Agregado(a)')], verbose_name='Parentesco'),
        ),
    ]
