# Generated by Django 2.0.4 on 2018-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20180515_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacaocredito',
            options={'verbose_name': '', 'verbose_name_plural': '23. Com relação aos créditos, como está a aplicação no lote?'},
        ),
        migrations.AlterModelOptions(
            name='atendimentosaude',
            options={'verbose_name': '', 'verbose_name_plural': '46. Onde é feito o atendimento à saúde para as famílias do assentamento?'},
        ),
        migrations.AlterModelOptions(
            name='atividadeextrativista',
            options={'verbose_name': '', 'verbose_name_plural': '29. Produtos de atividade extrativista do último ano agrícola'},
        ),
        migrations.AlterModelOptions(
            name='atividadefisica',
            options={'verbose_name': '', 'verbose_name_plural': '50. Quais são os esportes/atividades físicas praticados pelos familiares com maior frequência?'},
        ),
        migrations.AlterModelOptions(
            name='autodeclaracaoetnia',
            options={'verbose_name': 'Auto declaração', 'verbose_name_plural': '5. Quantos moradores se declaram'},
        ),
        migrations.AlterModelOptions(
            name='bemprodutivo',
            options={'verbose_name': 'Bem produtivo', 'verbose_name_plural': '22. Bens produtivos disponíveis no lote'},
        ),
        migrations.AlterModelOptions(
            name='beneficiosocial',
            options={'verbose_name': '', 'verbose_name_plural': '4. Quais os tipos de benefício?'},
        ),
        migrations.AlterModelOptions(
            name='bovinocultura',
            options={'verbose_name': '', 'verbose_name_plural': '31. Sobre o Efetivo Animal do último ano agrícola (Bovinocultura)'},
        ),
        migrations.AlterModelOptions(
            name='bovinoculturacorte',
            options={'verbose_name': '', 'verbose_name_plural': 'Descarte Animal - Bovinocultura de Corte'},
        ),
        migrations.AlterModelOptions(
            name='bovinoculturaleiteira',
            options={'verbose_name': '', 'verbose_name_plural': 'Descarte Animal - Bovinocultura Leiteira'},
        ),
        migrations.AlterModelOptions(
            name='construcaolote',
            options={'verbose_name': 'Construção', 'verbose_name_plural': '21. O que tem construído no lote?'},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='creditobancario',
            options={'verbose_name': '', 'verbose_name_plural': '24. Com relação aos créditos bancários, como está a aplicação na parcela?'},
        ),
        migrations.AlterModelOptions(
            name='cultura',
            options={'verbose_name': '', 'verbose_name_plural': '25. Agora falaremos sobre a produção/culturas, plantadas na sua lavoura/roça no último ano agrícola'},
        ),
        migrations.AlterModelOptions(
            name='destinolixodomestico',
            options={'verbose_name': '', 'verbose_name_plural': '42. Qual o destino do lixo doméstico não orgânico?'},
        ),
        migrations.AlterModelOptions(
            name='destinomaterialorganico',
            options={'verbose_name': '', 'verbose_name_plural': '43. Qual o destino do material orgânico?'},
        ),
        migrations.AlterModelOptions(
            name='documentolote',
            options={'verbose_name': '', 'verbose_name_plural': '1. Quais documentos o lote possui?'},
        ),
        migrations.AlterModelOptions(
            name='espacodisponivel',
            options={'verbose_name': '', 'verbose_name_plural': '52. No assentamento quais são os espaços disponíveis para a prática de esporte ou para a recreação?'},
        ),
        migrations.AlterModelOptions(
            name='estabelecimentoensino',
            options={'verbose_name': '', 'verbose_name_plural': '53. Que tipo de estabelecimento de ensino está disponível no assentamento?'},
        ),
        migrations.AlterModelOptions(
            name='estruturaorganizativa',
            options={'verbose_name': 'Estruturas organizativa', 'verbose_name_plural': '6. Das estruturas organizativas internas ao assentamento diga qual existe no assentamento e de quais os membros da família participam'},
        ),
        migrations.AlterModelOptions(
            name='familia',
            options={'verbose_name': 'Família', 'verbose_name_plural': 'Famílias'},
        ),
        migrations.AlterModelOptions(
            name='fonteagua',
            options={'verbose_name': '', 'verbose_name_plural': '11. De onde vem a água que abastece a família?'},
        ),
        migrations.AlterModelOptions(
            name='fruticultura',
            options={'verbose_name': '', 'verbose_name_plural': '27. Fruticultura referente ao último ano agrícola'},
        ),
        migrations.AlterModelOptions(
            name='licenciamentoambiental',
            options={'verbose_name': '', 'verbose_name_plural': 'Necessita de licenciamento ambiental para alguma atividade?'},
        ),
        migrations.AlterModelOptions(
            name='naopossuidocumento',
            options={'verbose_name': '', 'verbose_name_plural': '56. Com relação à documentação, quantas pessoas NÃO POSSUEM os documentos relacionados abaixo?'},
        ),
        migrations.AlterModelOptions(
            name='niveltecnologicoproducaoanimal',
            options={'verbose_name': '', 'verbose_name_plural': 'Sobre o Nível Tecnológico da Produção Animal'},
        ),
        migrations.AlterModelOptions(
            name='olericultura',
            options={'verbose_name': '', 'verbose_name_plural': '26. Olericulturas - Legumes e Verduras no último ano agrícola'},
        ),
        migrations.AlterModelOptions(
            name='opcaoensinoutilizada',
            options={'verbose_name': 'Opção de ensino utilizada:', 'verbose_name_plural': '55. No caso de não haver oferta de estabelecimento de ensino apropriado no assentamento, qual a opção utilizada pelos familiares?'},
        ),
        migrations.AlterModelOptions(
            name='origemanimal',
            options={'verbose_name': '', 'verbose_name_plural': '32. Sobre os produtos de origem animal produzidos no último ano agrícola'},
        ),
        migrations.AlterModelOptions(
            name='outracriacao',
            options={'verbose_name': '', 'verbose_name_plural': '31. Sobre o Efetivo Animal do último ano agrícola (Outras Criações)'},
        ),
        migrations.AlterModelOptions(
            name='praticaconservacionista',
            options={'verbose_name': '', 'verbose_name_plural': '41. Quais são as práticas conservacionistas praticadas na propriedade?'},
        ),
        migrations.AlterModelOptions(
            name='problemaambiental',
            options={'verbose_name': '', 'verbose_name_plural': '40. Quais são os problemas ambientais existentes no lote?'},
        ),
        migrations.AlterModelOptions(
            name='processadobeneficiado',
            options={'verbose_name': '', 'verbose_name_plural': '36. Sobre os produtos processados ou beneficiados no estabelecimento, no último ano agrícola (agroindústria)'},
        ),
        migrations.AlterModelOptions(
            name='producaoflorestal',
            options={'verbose_name': '', 'verbose_name_plural': '30. Produção Florestal do último ano agrícola'},
        ),
        migrations.AlterModelOptions(
            name='programasaude',
            options={'verbose_name': '', 'verbose_name_plural': '47. Quais os programas ou tipos de atendimento à saúde são disponibilizados no P.A?'},
        ),
        migrations.AlterModelOptions(
            name='rendatrabalhoforalote',
            options={'verbose_name': 'Renda de trabalho fora do lote', 'verbose_name_plural': '37. Sobre a renda de trabalho fora do lote'},
        ),
        migrations.AlterModelOptions(
            name='tratamentoagua',
            options={'verbose_name': '', 'verbose_name_plural': '12. Qual a forma tratamento da água para consumo?'},
        ),
        migrations.AlterModelOptions(
            name='usofrequente',
            options={'verbose_name': 'Faz o uso frequente de', 'verbose_name_plural': '49. Quais os tipos de usos frequentes?'},
        ),
        migrations.AddField(
            model_name='tratamentoagua',
            name='outros',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Outros (Especificar)'),
        ),
        migrations.AlterField(
            model_name='beneficiosocial',
            name='tipo_beneficio',
            field=models.IntegerField(choices=[(10, 'Aposentadoria por tempo de serviço/idade'), (20, 'Aposentadoria por invalidez'), (30, 'Auxílio maternidade'), (40, 'Bolsa família'), (50, 'Bolsa verde'), (60, 'Outros')], verbose_name='Benefício'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='abastecimento_agua_suficiente',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='14. A água que abastece a residência é suficiente?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='agua_para_animais_plantio',
            field=models.IntegerField(choices=[(10, "Sim, os animais vão até um curso d'água ou represa"), (20, "Sim, a água é puxada de um curso d'água ou represa"), (30, 'Sim, temos um poço exclusivo para os animais'), (40, 'Sim, é a mesma água que vem para a casa'), (50, 'Não há água para animais'), (60, 'Sim, existe água para plantio(s) irrigado(s)'), (70, 'Não existe água para plantio(s) irrigado(s)'), (80, 'Outros')], verbose_name='16. No lote tem água para os animais / Plantio?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area_preservacao_permanente',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='38. Existe Área de Preservação Permanente (APP) dentro do seu lote/parcela?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area_preservacao_permanente_cercada',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='39. A Área de Preservação Permanente está cercada ou isolada?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo_sipra',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Código SIPRA'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='frequencia_atividade_fisica',
            field=models.IntegerField(choices=[(10, 'Diariamente'), (20, 'Duas vezes por semana'), (30, 'Mais de duas vezes por semana'), (40, 'Não pratica')], verbose_name='51. Com que frequência praticam atividades físicas ou esportes?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='localizacao_fonte_agua',
            field=models.IntegerField(choices=[(1, 'Dentro do seu lote'), (2, 'Fora do seu lote')], verbose_name='13. Onde está localizada a fonte de água que abastece sua residência?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='moradia_assentamento',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='7. Possui moradia no assentamento?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='necessita_autoriacao_exploracao_florestal_queima_controlada',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='45. Necessita de autorização de exploração florestal e/ou queima controlada?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='oferta_transporte_interno',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não'), (99, 'Não se aplica')], verbose_name='54. Para a escola do assentamento há oferta de transporte interno?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='possui_pastagem_em_pastejo_rotacionado',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='34. Possui Pastagem em Pastejo Rotacionado?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='pratica_inseminacao_artificial_no_rebanho_leiteiro',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='35. Pratica inseminação aritificial no rebanho leiteiro?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='qualidade_servico_saude',
            field=models.IntegerField(choices=[(10, 'Ótimo'), (20, 'Bom'), (30, 'Ruim'), (40, 'Péssimo')], verbose_name='48. Como os moradores consideram o serviço de saúde no assentamento?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='quantas_familias_utilizam_mesma_fonte_agua',
            field=models.IntegerField(choices=[(10, 'Nenhuma'), (20, 'Uma outra família, além da sua família'), (30, 'Mais de uma')], verbose_name='15. Quantas famílias (além da sua) fazem o uso da mesma fonte de água que abastece o seu lote?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='recebe_beneficio_social',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='3. Algum dos membros da família recebe algum tipo de Benefício Social?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='regularidade_abastecimento_agua',
            field=models.IntegerField(choices=[(10, 'Sempre tem água'), (20, 'Falta água às vezes'), (30, 'Falta água com frequência'), (40, 'Nunca tem água')], verbose_name='17. Regularidade de abastecimento de água'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='situacao_cercado_lote',
            field=models.IntegerField(choices=[(10, 'Totalmente cercado, com divisões internas'), (20, 'Totalmente cercado, sem divisões internas'), (30, 'Parcialmente cercado'), (40, 'Não está cercado')], verbose_name='20. Como está cercado o lote?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='situacao_estrada_acesso',
            field=models.IntegerField(choices=[(10, 'Boa'), (20, 'Razoável'), (30, 'Ruim'), (40, 'Péssima')], verbose_name='19. Situação anual da estrada principal acesso ao lote?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_estrada_acesso',
            field=models.IntegerField(choices=[(10, 'Asfalto'), (20, 'Estrada cascalhada'), (30, 'Estrada de terra'), (40, 'Trilheiro'), (50, 'Inexistente')], verbose_name='18. Como é o acesso ao lote?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_instalacao_eletrica',
            field=models.IntegerField(blank=True, choices=[(10, 'Não instalada'), (20, 'Instalada apenas para moradia'), (30, 'Instalada para moradia e outros usos'), (40, 'Outros')], null=True, verbose_name='9. Instalação de energia elétrica?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_instalacao_sanitaria',
            field=models.IntegerField(blank=True, choices=[(10, 'Banheiro com fossa séptica'), (20, 'Banheiro com fossa negra'), (30, 'Privada / latrina'), (40, 'Nenhuma')], null=True, verbose_name='10. Qual é o tipo de instalação sanitária?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_parede_externa',
            field=models.IntegerField(blank=True, choices=[(10, 'Alvenaria'), (20, 'Tábuas / Madeira'), (30, 'Tapumes ou chapas de madeira'), (40, 'Folha de zinco'), (50, 'Barro ou adobe'), (60, 'Lona'), (70, 'Outros')], null=True, verbose_name='8. Qual tipo de parede externa predominante da moradia?'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tratamentoagua',
            name='tratamento_agua',
            field=models.IntegerField(choices=[(10, 'Não há tratamento'), (20, 'Cloração'), (30, 'Fervura'), (40, 'Filtragem'), (50, 'Dessalinização'), (60, 'Outros')], verbose_name='Forma de tratamento'),
        ),
    ]
