# Generated by Django 2.0.5 on 2018-05-29 22:36

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_projetoassentamento_capacidade_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField(verbose_name='Número do Contrato')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do Contrato')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_contrato_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_contrato_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_contrato_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'verbose_name': 'Campo Diagnóstico', 'verbose_name_plural': 'Campo Diagnósticos'},
        ),
        migrations.AlterField(
            model_name='lote',
            name='area_pastejo_rotacionado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tamanho da área em sistema de Pastejo Rotacionado (ha)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='necessita_licenciamento_ambiental',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Necessita de licenciamento ambiental de atividade?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='possui_capineira',
            field=models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Possui Capineira?'),
        ),
        migrations.AlterField(
            model_name='producaoflorestal',
            name='quantidade_produzida_ano',
            field=models.IntegerField(verbose_name='Quantidade produzida/ano'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor R$'),
        ),
    ]
