# Generated by Django 2.0.5 on 2018-07-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180727_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaovegetal',
            name='classificacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classificação'),
        ),
    ]
