# Generated by Django 2.0.5 on 2018-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_model_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoassentamento',
            name='capacidade_projeto',
            field=models.PositiveIntegerField(verbose_name='Capacidade do Projeto'),
        ),
    ]
