# Generated by Django 2.0.5 on 2018-05-29 23:52

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180529_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoassentamento',
            name='contrato2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_assentamento', to='core.Contrato', verbose_name='Contrato', null=True),
            preserve_default=False,
        ),
    ]
