# Generated by Django 2.0.5 on 2018-07-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180727_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinolixodomestico',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='destinolixodomestico',
            name='desativado_por',
        ),
        migrations.RemoveField(
            model_name='destinolixodomestico',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='destinolixodomestico',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='destinomaterialorganico',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='destinomaterialorganico',
            name='desativado_por',
        ),
        migrations.RemoveField(
            model_name='destinomaterialorganico',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='destinomaterialorganico',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='desativado_por',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='rendatrabalhoforalote',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='rendatrabalhoforalote',
            name='desativado_por',
        ),
        migrations.RemoveField(
            model_name='rendatrabalhoforalote',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='rendatrabalhoforalote',
            name='modificado_por',
        ),
        migrations.AlterField(
            model_name='producaoanimal',
            name='valor_cabeca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='R$/Cabeça'),
        ),
        migrations.DeleteModel(
            name='DestinoLixoDomestico',
        ),
        migrations.DeleteModel(
            name='DestinoMaterialOrganico',
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
        migrations.DeleteModel(
            name='RendaTrabalhoForaLote',
        ),
    ]
