# Generated by Django 2.0.5 on 2018-05-29 23:52

from django.db import migrations, models
import django.db.models.deletion

def popular_dados_contrato(apps, schema_editor):
    Contrato = apps.get_model('core', 'Contrato')
    ProjetoAssentamento = apps.get_model('core', 'ProjetoAssentamento')
    User = apps.get_model('users', 'User')
    usuario = User.objects.filter(is_active=True).first()

    c1 = Contrato(numero=10000, ano=2015, cadastrado_por=usuario)
    c2 = Contrato(numero=11000, ano=2015, cadastrado_por=usuario)
    c3 = Contrato(numero=18000, ano=2015, cadastrado_por=usuario)
    contratos = [c1, c2, c3]
    print(contratos)
    for c in contratos:
        c.modificado_por = c.cadastrado_por
        c.modificado_em = c.cadastrado_em
    Contrato.objects.bulk_create(contratos)

    projetos = ProjetoAssentamento.objects.all()
    for p in projetos:
        if p.contrato == 10:
            p.contrato2 = c1
        if p.contrato == 11:
            p.contrato2 = c2
        if p.contrato == 18:
            p.contrato2 = c3
        p.save()


def reverse_code(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projetoassentamento_contrato2'),
    ]

    operations = [
        migrations.RunPython(
          code=popular_dados_contrato,
          reverse_code=reverse_code,
          atomic=True,
        ),
    ]
