# Generated by Django 2.0.5 on 2018-07-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180730_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaoanimal',
            name='valor_cabeca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='R$/Cabeça'),
        ),
    ]
