# Generated by Django 2.0.5 on 2018-05-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrar_dados'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('numero', 'ano')},
        ),
    ]
