# Generated by Django 2.0.5 on 2018-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180730_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaovegetal',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor (R$)'),
        ),
    ]
