# Generated by Django 2.0.5 on 2018-05-30 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180529_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetoassentamento',
            name='contrato2',
        ),
        migrations.AlterField(
            model_name='projetoassentamento',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_assentamento', to='core.Contrato', verbose_name='Contrato'),
        ),
        # migrations.RemoveField(
        #     model_name='projetoassentamento',
        #     name='contrato',
        # ),
        # migrations.RenameField(
        #     model_name='projetoassentamento',
        #     old_name='contrato2',
        #     new_name='contrato',
        # ),
    ]
