# Generated by Django 2.0.5 on 2018-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180730_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaoanimal',
            name='valor_cabeca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='R$/Cabeça'),
        ),
    ]
