# Generated by Django 2.0.5 on 2018-06-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180529_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='ocupante_irregular',
            field=models.IntegerField(choices=[(10, 'Regular'), (20, 'Irregular'), (30, 'Bloqueado')], verbose_name='Ocupante irregular?'),
        ),
    ]
