# Generated by Django 2.0.5 on 2018-06-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180607_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='banda_coordenada',
            field=models.CharField(default='', max_length=30, verbose_name='Banda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='data_visita',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Visita'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_homologacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Homologação'),
        ),
    ]
