# Generated by Django 2.0.5 on 2018-06-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180607_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='banda_coordenada',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Banda'),
        ),
    ]
