# Generated by Django 2.0.5 on 2018-06-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180607_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='teste',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teste'),
        ),
    ]
