# Generated by Django 2.0.5 on 2018-06-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_familia_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='teste',
        ),
    ]
