# Generated by Django 2.0.5 on 2018-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_familia_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='destino_lixo_domestico_nao_organico',
            field=models.IntegerField(choices=[(10, 'Espalhado no lote'), (20, 'Queima'), (30, 'Enterra'), (40, "Joga nos cursos d'água"), (50, 'Recicla/reaproveita lixo inorgânico'), (60, 'Deposita a céu aberto no lote'), (999, 'Não se aplica')], default=0, verbose_name='Qual o destino do lixo doméstico não orgânico?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='destino_material_organico',
            field=models.IntegerField(choices=[(10, 'Uso para alimentação de animais'), (20, 'Faz compostagem'), (30, 'Enterra junto com inorgânico'), (40, 'Deposita a céu aberto no lote'), (999, 'Não se aplica')], default=0, verbose_name='Qual o destino do material orgânico?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descarteanimal',
            name='canal_comercializacao',
            field=models.IntegerField(blank=True, choices=[(10, 'Venda para outro produtor'), (20, 'Entrega para frigorífico/açougue'), (30, 'Venda para agentes "atravessadores"'), (40, 'Outros')], null=True, verbose_name='Formas/Canais de Comercialização'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='ocupante_irregular',
            field=models.IntegerField(choices=[(10, 'Regular'), (20, 'Irregular'), (30, 'Bloqueado')], verbose_name='Status do Ocupante'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='canal_comercializacao',
            field=models.IntegerField(blank=True, choices=[(10, 'Venda direta ao consumidor (de casa em casa)'), (20, 'Venda em feiras'), (30, 'Entrega para supermercados, mercearias, açougues, etc'), (40, 'Venda p/ indústrias, e/ou agroindústrias (laticínios etc)'), (50, 'Venda para agentes "atravessadores"'), (60, 'Outros')], null=True, verbose_name='Formas/Canais de Comercialização'),
        ),
        migrations.AlterField(
            model_name='producaovegetal',
            name='producao_unidade_medida',
            field=models.IntegerField(blank=True, choices=[(1, 'Kg'), (2, 'un')], null=True, verbose_name='Unidade de medida'),
        ),
    ]
