# Generated by Django 2.0.5 on 2018-07-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180628_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='destino_lixo_domestico_nao_organico',
            field=models.IntegerField(choices=[(10, 'Espalhado no lote'), (20, 'Queima'), (30, 'Enterra'), (40, "Joga nos cursos d'água"), (50, 'Recicla/reaproveita lixo inorgânico'), (60, 'Deposita a céu aberto no lote'), (999, 'Não se aplica')], verbose_name='42. Qual o destino do lixo doméstico não orgânico?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='destino_material_organico',
            field=models.IntegerField(choices=[(10, 'Uso para alimentação de animais'), (20, 'Faz compostagem'), (30, 'Enterra junto com inorgânico'), (40, 'Deposita a céu aberto no lote'), (999, 'Não se aplica')], verbose_name='43. Qual o destino do material orgânico?'),
        ),
    ]
