# Generated by Django 2.0.5 on 2018-07-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180710_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='nome',
        ),
    ]
